name: dpod-workflow

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  aws-ecr-config:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build tag and push image to Amazon ECR
        run: |
          echo "${{ steps.login-ecr.outputs.registry }}"
          docker build -t 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v4 .
          docker push 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v4