name: dpod-workflow

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  aws-ecr-config:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build tag and push image to Amazon ECR
        run: |
          echo "${{ steps.login-ecr.outputs.registry }}"
          docker build -t 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v3 .
          docker push 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v3