name: dpod-workflow

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  aws-ecr-config:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   env:
      #     # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     # ECR_REGISTRY: 009214174302.dkr.ecr.us-west-2.amazonaws.com
      #     ECR_REGISTRY: 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     # echo "${{ steps.login-ecr.outputs.registry }}"
      #     # ls -la
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # - run: docker build --tag ypy .

      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2

      - name: Push to ECR
        id: ecr-empuje
        # uses: jwalton/gh-ecr-push@v1
        # with:
        #   access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   region: us-west-2
        run: |
          docker tag ypy:latest ${{ steps.ecr.outputs.account }}.dkr.ecr.us-west-2.amazonaws.com/ypy:latest
          docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-west-2.amazonaws.com/ypy:latest

          # local-image: ypy
          # # image: my-image:dev-${{ github.sha }}
          # image: ypy
