name: dpod-workflow

env: {}

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      # - name: Check out source code
      #   uses: actions/checkout@v2

      # - name: Tell secret
      #   env:
      #     MY_VAR: Hi there! My name is
      #     FIRST_NAME: Mona
      #     MIDDLE_NAME: The
      #     LAST_NAME: Octocat
      #     FEELZ: ${{ secrets.FEELINGS }}
      #   run: |
      #     echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME $FEELZ.