name: dpod-workflow

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main

jobs:
  aws-ecr-config:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        id: git-checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: outputtts
        id: outputts
        run:
          echo "--------------------------------:::::::::::::::::::"
          echo "registry is ${{ steps.login-ecr.outputs.registry }}"
      # - name: Build tag and push image to Amazon ECR
      #   run: |
      #     echo "${{ steps.login-ecr.outputs.registry }}"
      #     docker build -t 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v3 .
      #     docker push 009214174302.dkr.ecr.us-west-2.amazonaws.com/ypy:v3
      # - name: Build, tag, and push image to Amazon ECR
        # env:
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # ECR_REPOSITORY: ypy
          # IMAGE_TAG: ${{ github.sha }}
        # run: |
          # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG